import type { Candidate, Resident, User } from "./types";

export const INITIAL_RESIDENTS: Resident[] = [
  {
    id: "1",
    nik: "320101001",
    name: "Budi Santoso",
    email: "budi.santoso@example.com",
    address: "Jl. Merpati No. 1",
    rt: "001",
    rw: "05",
    phoneNumber: "081234567890",
    status: "Aktif",
    block: "A",
    hasVoted: true,
    isPresent: true,
  },
  {
    id: "2",
    nik: "320101002",
    name: "Siti Aminah",
    email: "siti.aminah@example.com",
    address: "Jl. Merpati No. 2",
    rt: "001",
    rw: "05",
    phoneNumber: "081234567891",
    status: "Aktif",
    block: "A",
    hasVoted: false,
    isPresent: false,
  },
  {
    id: "3",
    nik: "320101003",
    name: "Rudi Hermawan",
    email: "rudi.hermawan@example.com",
    address: "Jl. Elang No. 10",
    rt: "002",
    rw: "05",
    phoneNumber: "081234567892",
    status: "Aktif",
    block: "B",
    hasVoted: true,
    isPresent: true,
  },
  {
    id: "4",
    nik: "320101004",
    name: "Dewi Lestari",
    email: "dewi.lestari@example.com",
    address: "Jl. Elang No. 12",
    rt: "002",
    rw: "05",
    phoneNumber: "081234567893",
    status: "Pindah",
    block: "B",
    hasVoted: false,
    isPresent: true,
  },
  {
    id: "5",
    nik: "320101005",
    name: "Agus Salim",
    email: "agus.salim@example.com",
    address: "Jl. Pipit No. 5",
    rt: "003",
    rw: "05",
    phoneNumber: "081234567894",
    status: "Aktif",
    block: "C",
    hasVoted: true,
    isPresent: true,
  },
  {
    id: "6",
    nik: "320101006",
    name: "Eko Prasetyo",
    email: "eko.prasetyo@example.com",
    address: "Jl. Pipit No. 7",
    rt: "003",
    rw: "05",
    phoneNumber: "081234567895",
    status: "Aktif",
    block: "C",
    hasVoted: false,
    isPresent: false,
  },
  {
    id: "7",
    nik: "320101007",
    name: "Ratna Sari",
    email: "ratna.sari@example.com",
    address: "Jl. Kutilang No. 3",
    rt: "004",
    rw: "05",
    phoneNumber: "081234567896",
    status: "Aktif",
    block: "D",
    hasVoted: true,
    isPresent: true,
  },
  {
    id: "8",
    nik: "320101008",
    name: "Bambang Wijaya",
    email: "bambang.wijaya@example.com",
    address: "Jl. Kutilang No. 5",
    rt: "004",
    rw: "05",
    phoneNumber: "081234567897",
    status: "Pindah",
    block: "D",
    hasVoted: false,
    isPresent: false,
  },
  {
    id: "9",
    nik: "320101009",
    name: "Sri Wahyuni",
    email: "sri.wahyuni@example.com",
    address: "Jl. Gelatik No. 8",
    rt: "005",
    rw: "05",
    phoneNumber: "081234567898",
    status: "Aktif",
    block: "E",
    hasVoted: true,
    isPresent: true,
  },
  {
    id: "10",
    nik: "320101010",
    name: "Hendra Gunawan",
    email: "hendra.gunawan@example.com",
    address: "Jl. Gelatik No. 9",
    rt: "005",
    rw: "05",
    phoneNumber: "081234567899",
    status: "Meninggal",
    block: "E",
    hasVoted: false,
    isPresent: true,
  },
];

export const INITIAL_CANDIDATES: Candidate[] = [
  {
    id: "c1",
    number: 1,
    name: "H. Ahmad Sobari",
    vision: "Mewujudkan lingkungan RW 05 yang aman, bersih, dan religius.",
    mission: "1. Mengaktifkan Siskamling.\n2. Program Jumat Bersih.",
    imageUrl: "https://i.pravatar.cc/300?u=ahmad",
    voteCount: 18,
  },
  {
    id: "c2",
    number: 2,
    name: "Ir. Joko Susilo",
    vision: "RW 05 Digital dan Transparan.",
    mission: "1. Laporan keuangan online.\n2. WiFi gratis di pos ronda.",
    imageUrl: "https://i.pravatar.cc/300?u=joko",
    voteCount: 14,
  },
  {
    id: "c3",
    number: 3,
    name: "Ibu Linda Kusuma, S.Pd",
    vision: "Pemberdayaan Keluarga dan Kesehatan Lingkungan.",
    mission: "1. Optimalisasi Posyandu.\n2. Bank Sampah Mandiri.",
    imageUrl: "https://i.pravatar.cc/300?u=linda",
    voteCount: 10,
  },
];

export const getInitialUsers = (): User[] => [
  {
    id: "super-admin",
    name: "Super Administrator",
    role: "super_admin",
    username: process.env.SUPER_ADMIN_USERNAME || "superadmin",
    password: process.env.SUPER_ADMIN_PASSWORD || "superadmin",
  },
];
